services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_DATABASE: zoo2_prod
      MARIADB_ROOT_PASSWORD:  ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  app:
    build: .
    restart: always
    ports:
      - "3010:3000"
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: "mysql://root:${DB_PASSWORD}@db:3306/zoo2_prod"
    depends_on:
      - db

volumes:
  db_data: