import { PrismaClient, SectorArea, RequirementType } from "@prisma/client";

const prisma = new PrismaClient();

type RequirementInput = {
  type: RequirementType;
  requiredLevel?: number;
  itemName: string;
  sortOrder: number;
};

type CollectionInput = {
  identifier: string;
  stars: number;
  area: SectorArea;
  name: string; // English name (used for all locales for now)
  requirements: RequirementInput[];
};

function animal(level: number, name: string, sortOrder: number): RequirementInput {
  return { type: "ANIMAL", requiredLevel: level, itemName: name, sortOrder };
}

function decoration(name: string, sortOrder: number): RequirementInput {
  return { type: "DECORATION", itemName: name, sortOrder };
}

const collections: CollectionInput[] = [
  // ===== MAIN ZOO - 1 star =====
  {
    identifier: "silver_fox",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Silver Fox",
    requirements: [
      animal(2, "Chimpanzee", 0),
      animal(2, "Wild Boar", 1),
      animal(2, "Koala", 2),
      animal(2, "Red Fox", 3),
      animal(2, "Moose", 4),
      animal(2, "Red Panda", 5),
    ],
  },
  {
    identifier: "piebald_peafowl",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Piebald Peafowl",
    requirements: [
      animal(2, "Giant Tortoise", 0),
      animal(2, "Peafowl", 1),
      animal(2, "Red Kangaroo", 2),
      animal(2, "Plains Zebra", 3),
      animal(2, "Flamingo", 4),
      animal(2, "Golden Pheasant", 5),
    ],
  },
  {
    identifier: "black_white_rabbit",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Black & White Rabbit",
    requirements: [
      animal(2, "Rabbit", 0),
      animal(2, "Domestic Goat", 1),
      animal(2, "Horse", 2),
      animal(2, "Domestic Pig", 3),
      animal(2, "Sheep", 4),
      animal(2, "Giant Panda", 5),
    ],
  },
  {
    identifier: "blonde_kodiak_bear",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Blonde Kodiak Bear",
    requirements: [
      animal(3, "Kodiak Bear", 0),
      animal(3, "Bald Eagle", 1),
      animal(3, "Leopard", 2),
      animal(3, "Lynx", 3),
      animal(3, "Wolf", 4),
      animal(3, "Alpaca", 5),
    ],
  },
  {
    identifier: "brown_panda",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Brown Panda",
    requirements: [
      animal(3, "Domestic Pig (Brown and White)", 0),
      animal(3, "Rabbit (Black and White)", 1),
      animal(3, "Koala (Brown)", 2),
      animal(3, "Goat (White)", 3),
      animal(3, "Horse (Dapple-Gray)", 4),
      animal(3, "Sheep (Brown)", 5),
    ],
  },
  {
    identifier: "white_crocodile",
    stars: 1,
    area: "MAIN_ZOO",
    name: "White Crocodile",
    requirements: [
      animal(3, "Giant Tortoise", 0),
      animal(3, "Alligator Snapping Turtle", 1),
      animal(3, "Green Anaconda", 2),
      animal(3, "Nile Crocodile", 3),
      animal(3, "Komodo Dragon", 4),
    ],
  },
  {
    identifier: "pink_hippo",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Pink Hippo",
    requirements: [
      animal(3, "Lion", 0),
      animal(3, "Common Ostrich", 1),
      animal(3, "Fennec Fox", 2),
      animal(3, "Reticulated Giraffe", 3),
      animal(3, "White Rhinoceros", 4),
      animal(3, "Hippopotamus", 5),
    ],
  },
  {
    identifier: "jaguar_panther",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Jaguar (Panther)",
    requirements: [
      animal(3, "Scarlet Macaw", 0),
      animal(3, "Panther", 1),
      animal(3, "Flying Fox", 2),
      animal(3, "Green Anaconda", 3),
      animal(3, "Nile Crocodile", 4),
      animal(3, "Komodo Dragon", 5),
    ],
  },
  {
    identifier: "red_sable",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Red Sable",
    requirements: [
      animal(2, "Mountain Gorilla", 0),
      animal(2, "Lar Gibbon", 1),
      animal(2, "King Eider", 2),
      animal(2, "Pronghorn", 3),
      animal(2, "Red River Hog", 4),
      animal(2, "Maikong", 5),
      animal(2, "Leopard Seal", 6),
      animal(2, "Sable", 7),
      animal(2, "Grey-Crowned Crane", 8),
    ],
  },
  {
    identifier: "common_genet_brown",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Common Genet (Brown)",
    requirements: [
      animal(2, "Meerkat", 0),
      animal(2, "Owston's Palm Civet", 1),
      animal(2, "White-Tailed Mongoose", 2),
      animal(2, "African Civet", 3),
      animal(2, "Banded Mongoose", 4),
      animal(2, "Binturong", 5),
      animal(2, "Common Genet", 6),
    ],
  },
  {
    identifier: "black_capybara",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Black Capybara",
    requirements: [
      animal(2, "Capybara", 0),
      animal(2, "Beaver", 1),
      animal(2, "Domestic Pig", 2),
      animal(2, "Giant Tortoise", 3),
      animal(2, "Armadillo", 4),
      animal(2, "Panther", 5),
      animal(2, "Green Anaconda", 6),
    ],
  },
  {
    identifier: "red_wolf",
    stars: 1,
    area: "MAIN_ZOO",
    name: "Red Wolf",
    requirements: [
      animal(3, "Wolf", 0),
      animal(3, "Tundra Wolf", 1),
      animal(3, "Arctic Wolf", 2),
      animal(3, "African Wild Dog", 3),
      animal(3, "Bush Dog", 4),
      animal(3, "Maikong", 5),
      animal(3, "Red Fox", 6),
      animal(3, "Arctic Fox", 7),
    ],
  },

  // ===== MAIN ZOO - 2 star =====
  {
    identifier: "white_moose",
    stars: 2,
    area: "MAIN_ZOO",
    name: "White Moose",
    requirements: [
      animal(4, "Wild Boar", 0),
      animal(4, "Koala", 1),
      animal(4, "Red Fox", 2),
      animal(4, "Koala (Brown)", 3),
      animal(4, "Moose", 4),
      animal(4, "Owston's Palm Civet", 5),
      animal(4, "Okapi", 6),
      animal(4, "Moon Bear", 7),
      animal(4, "European Badger", 8),
    ],
  },
  {
    identifier: "white_zebra",
    stars: 2,
    area: "MAIN_ZOO",
    name: "White Zebra",
    requirements: [
      animal(5, "Red Kangaroo", 0),
      animal(5, "Plains Zebra", 1),
      animal(5, "Flamingo", 2),
      animal(5, "Piebald Peafowl", 3),
      animal(5, "Armadillo", 4),
      animal(5, "Reindeer", 5),
      animal(5, "Bongo Antelope", 6),
      animal(5, "American Bison", 7),
    ],
  },
  {
    identifier: "spotted_alpaca",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Spotted Alpaca",
    requirements: [
      animal(4, "Kodiak Bear", 0),
      animal(4, "Lynx", 1),
      animal(4, "Kodiak Bear (Blonde)", 2),
      animal(4, "Wolf", 3),
      animal(4, "Golden Takin", 4),
      animal(4, "Leopard", 5),
      animal(4, "Alpaca", 6),
      animal(4, "Baboon", 7),
      animal(4, "African Wild Ass", 8),
    ],
  },
  {
    identifier: "white_wild_dog",
    stars: 2,
    area: "MAIN_ZOO",
    name: "White Wild Dog",
    requirements: [
      animal(5, "Wolf", 0),
      animal(5, "Fennec Fox", 1),
      animal(5, "Red Fox (Silver)", 2),
      animal(5, "Tundra Wolf", 3),
      animal(5, "African Wild Dog", 4),
      animal(5, "Arctic Fox", 5),
      animal(5, "Red Fox", 6),
    ],
  },
  {
    identifier: "white_nosed_coati",
    stars: 2,
    area: "MAIN_ZOO",
    name: "White-Nosed Coati",
    requirements: [
      animal(5, "Giant Panda", 0),
      animal(5, "Kodiak Bear", 1),
      animal(5, "Raccoon", 2),
      animal(5, "Red Panda", 3),
      animal(5, "Kinkajou", 4),
      animal(5, "Coati", 5),
      animal(5, "Moon Bear", 6),
      animal(5, "Ringtail", 7),
      animal(5, "Polar Bear", 8),
    ],
  },
  {
    identifier: "white_sulphur_crested_cockatoo",
    stars: 2,
    area: "MAIN_ZOO",
    name: "White Sulphur-Crested Cockatoo",
    requirements: [
      animal(5, "Bald Eagle", 0),
      animal(5, "Common Ostrich", 1),
      animal(5, "Scarlet Macaw", 2),
      animal(5, "Sulphur-Crested Cockatoo", 3),
      animal(5, "Toco Toucan", 4),
      animal(5, "Eastern Grass Owl", 5),
      animal(5, "Western Crowned Pigeon", 6),
      animal(5, "Secretarybird", 7),
    ],
  },
  {
    identifier: "summer_arctic_fox",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Summer Arctic Fox",
    requirements: [
      animal(4, "Snow Hare", 0),
      animal(4, "Polar Bear", 1),
      animal(4, "Arctic Fox", 2),
      animal(4, "Emperor Penguin", 3),
      animal(4, "Wolverine", 4),
      animal(4, "Arctic Wolf", 5),
    ],
  },
  {
    identifier: "black_swan",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Black Swan",
    requirements: [
      animal(5, "Domestic Pig", 0),
      animal(5, "Sheep", 1),
      animal(5, "Giant Panda", 2),
      animal(5, "Raccoon", 3),
      animal(5, "White Stork", 4),
      animal(5, "Swan", 5),
      animal(5, "Alligator Snapping Turtle", 6),
      animal(5, "Tapir", 7),
      animal(5, "Beaver", 8),
    ],
  },
  {
    identifier: "mandarin_duck_white",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Mandarin Duck (White)",
    requirements: [
      animal(2, "Mandarin Duck", 0),
      animal(2, "King Eider", 1),
      animal(2, "Swan", 2),
      animal(2, "Swan (Black)", 3),
      animal(2, "Snowy Owl", 4),
      animal(2, "Kakapo", 5),
      animal(2, "Harpy Eagle", 6),
    ],
  },
  {
    identifier: "brown_brushtail_possum",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Brown Brushtail Possum",
    requirements: [
      animal(2, "Red Kangaroo", 0),
      animal(2, "Koala", 1),
      animal(2, "Goodfellow Tree Kangaroo", 2),
      animal(2, "Quokka", 3),
      animal(2, "Common Wombat", 4),
      animal(2, "Matschie's Tree Kangaroo", 5),
      animal(2, "Brushtail Possum", 6),
    ],
  },
  {
    identifier: "green_indian_star_tortoise",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Green Indian Star Tortoise",
    requirements: [
      animal(5, "Giant Tortoise", 0),
      animal(5, "Alligator Snapping Turtle", 1),
      animal(5, "Hawksbill Sea Turtle", 2),
      animal(5, "Indian Star Tortoise", 3),
      animal(5, "Mata Mata", 4),
    ],
  },
  {
    identifier: "ruffed_lemur",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Ruffed Lemur (Black-and-White)",
    requirements: [
      animal(4, "Red-Ruffed Lemur", 0),
      animal(4, "Orangutan", 1),
      animal(4, "Patas Monkey", 2),
      animal(4, "Lion Tamarin", 3),
      animal(4, "Panamanian White-Faced Capuchin", 4),
      animal(4, "De Brazza's Monkey", 5),
      animal(4, "Golden Snub-Nosed Monkey", 6),
      animal(4, "Black Bearded Saki", 7),
    ],
  },
  {
    identifier: "leucistic_emu",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Leucistic Emu",
    requirements: [
      animal(4, "Emu", 0),
      animal(4, "Common Ostrich", 1),
      animal(4, "Somali Ostrich", 2),
      animal(4, "Southern Cassowary", 3),
      animal(4, "Peafowl", 4),
      animal(4, "Flamingo", 5),
      animal(4, "Shoebill", 6),
      animal(4, "Emperor Penguin", 7),
    ],
  },
  {
    identifier: "cougar_white",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Cougar (White)",
    requirements: [
      animal(5, "Cougar", 0),
      animal(5, "Lion", 1),
      animal(5, "Lynx", 2),
      animal(5, "Panther", 3),
      animal(5, "Snow Leopard", 4),
      animal(5, "Jaguarundi (Black)", 5),
      animal(5, "Jaguarundi (Red)", 6),
      animal(5, "Siberian Tiger", 7),
    ],
  },
  {
    identifier: "ethiopian_wolf_black",
    stars: 2,
    area: "MAIN_ZOO",
    name: "Ethiopian Wolf (Black)",
    requirements: [
      animal(4, "Wolf", 0),
      animal(4, "Ethiopian Wolf", 1),
      animal(4, "Maned Wolf", 2),
      animal(4, "Tundra Wolf", 3),
      animal(4, "Arctic Wolf", 4),
      animal(4, "African Wild Dog", 5),
      animal(4, "Black-Backed Jackal", 6),
      animal(4, "Dhole", 7),
      animal(4, "Dingo", 8),
    ],
  },

  // ===== MAIN ZOO - 3 star =====
  {
    identifier: "white_reindeer",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Reindeer",
    requirements: [
      animal(2, "Reindeer", 0),
      animal(2, "Snow Leopard", 1),
      decoration("Ice Swan", 2),
      decoration("Beautiful Christmas Tree", 3),
      decoration("Nutcracker Sculpture", 4),
      decoration("Poinsettia", 5),
      decoration("Santa Sculpture", 6),
      decoration("Christmas Sleigh", 7),
      decoration("Snowman", 8),
    ],
  },
  {
    identifier: "harlequin_rabbit",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Harlequin Rabbit",
    requirements: [
      decoration("Rabbit Statue", 0),
      decoration("Goat Statue", 1),
      decoration("Horse Statue", 2),
      decoration("Sheep Statue", 3),
      decoration("Giant Panda Statue", 4),
    ],
  },
  {
    identifier: "maned_wolf",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Maned Wolf",
    requirements: [
      animal(10, "Domestic Pig (Brown and White)", 0),
      animal(10, "Rabbit (Black and White)", 1),
      animal(10, "Koala (Brown)", 2),
      animal(10, "Giant Panda (Brown)", 3),
      animal(10, "Peafowl (Piebald)", 4),
      animal(10, "Red Fox (Silver)", 5),
      animal(10, "Kodiak Bear (Blonde)", 6),
      animal(10, "Plains Zebra (White)", 7),
      animal(10, "Nile Crocodile (White)", 8),
    ],
  },
  {
    identifier: "white_gorilla",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Gorilla",
    requirements: [
      animal(8, "Lar Gibbon", 0),
      animal(8, "Mountain Gorilla", 1),
      animal(8, "Red-Ruffed Lemur", 2),
      animal(8, "Ring-Tailed Lemur", 3),
      animal(8, "Orangutan", 4),
      animal(8, "Mandrill", 5),
      animal(8, "Baboon", 6),
      animal(8, "Chimpanzee", 7),
    ],
  },
  {
    identifier: "black_gibbon",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Black Gibbon",
    requirements: [
      animal(6, "Scarlet Macaw", 0),
      animal(6, "Panther", 1),
      animal(6, "Flying Fox", 2),
      animal(6, "Green Anaconda", 3),
      animal(6, "Nile Crocodile", 4),
      animal(6, "Komodo Dragon", 5),
      animal(6, "Toco Toucan", 6),
      animal(6, "Mandrill", 7),
    ],
  },
  {
    identifier: "white_lion",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Lion",
    requirements: [
      animal(7, "Lion", 0),
      animal(7, "Bactrian Camel", 1),
      animal(7, "Meerkat", 2),
      animal(7, "Hippopotamus (Pink)", 3),
      animal(7, "Northern Red-Billed Hornbill", 4),
      animal(7, "Warthog", 5),
      animal(7, "Spotted Hyena", 6),
      animal(7, "African Elephant", 7),
    ],
  },
  {
    identifier: "white_tiger",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Tiger",
    requirements: [
      animal(8, "Owston's Palm Civet", 0),
      animal(8, "Leopard", 1),
      animal(8, "Bengal Tiger", 2),
      animal(8, "Caracal", 3),
      animal(8, "Ocelot", 4),
      animal(8, "Lion (White)", 5),
      animal(8, "Canadian Lynx", 6),
      animal(8, "Panther (Jaguar)", 7),
      animal(8, "Fishing Cat", 8),
    ],
  },
  {
    identifier: "ermine",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Ermine",
    requirements: [
      animal(7, "Raccoon", 0),
      animal(7, "Red Panda", 1),
      animal(7, "Kinkajou", 2),
      animal(7, "Stoat", 3),
      animal(7, "European Badger", 4),
      animal(7, "Ringtail", 5),
      animal(7, "Coati (White-Nosed)", 6),
      animal(7, "Spotted Skunk", 7),
    ],
  },
  {
    identifier: "maned_wolf_2",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Maned Wolf 2",
    requirements: [
      animal(10, "Hippopotamus (Pink)", 0),
      animal(10, "Moose (White)", 1),
      animal(10, "Sulphur-Crested Cockatoo (White)", 2),
      animal(10, "Mountain Gorilla (White)", 3),
      animal(10, "Lar Gibbon (Black)", 4),
      animal(10, "Alpaca (Spotted)", 5),
      animal(10, "Bengal Tiger (White)", 6),
      animal(10, "Lion (White)", 7),
      animal(10, "African Wild Dog (White)", 8),
    ],
  },
  {
    identifier: "american_badger",
    stars: 3,
    area: "MAIN_ZOO",
    name: "American Badger",
    requirements: [
      animal(10, "Kinkajou", 0),
      animal(10, "European Badger", 1),
      animal(10, "Wolverine", 2),
      animal(10, "Marbled Polecat", 3),
      animal(10, "Giant Otter", 4),
      animal(10, "Sea Otter", 5),
      animal(10, "Stoat", 6),
      animal(10, "Maned Wolf", 7),
    ],
  },
  {
    identifier: "american_badger_2",
    stars: 3,
    area: "MAIN_ZOO",
    name: "American Badger 2",
    requirements: [
      animal(10, "Plains Zebra (Black)", 0),
      animal(10, "Plains Zebra (White)", 1),
      animal(10, "Pronghorn", 2),
      animal(10, "Dikdik", 3),
      animal(10, "Llama", 4),
      animal(10, "Caracal", 5),
      animal(10, "Oryx", 6),
      animal(10, "Maned Wolf", 7),
    ],
  },
  {
    identifier: "douc",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Douc",
    requirements: [
      animal(10, "Chimpanzee", 0),
      animal(10, "Baboon", 1),
      animal(10, "Ring-Tailed Lemur", 2),
      animal(10, "Panamanian White-Faced Capuchin", 3),
      animal(10, "Lion Tamarin", 4),
      animal(10, "Red-Ruffed Lemur", 5),
      animal(10, "Squirrel Monkey", 6),
      animal(10, "Mandrill", 7),
      animal(10, "Patas Monkey", 8),
    ],
  },
  {
    identifier: "great_spotted_kiwi",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Great Spotted Kiwi",
    requirements: [
      animal(7, "Reticulated Giraffe", 0),
      animal(7, "Ocelot", 1),
      animal(7, "Rabbit (Spotted)", 2),
      animal(7, "Fallow Deer", 3),
      animal(7, "Cuscus", 4),
      animal(7, "Spotted Skunk", 5),
      animal(7, "African Wild Dog", 6),
      animal(7, "Clouded Leopard", 7),
      animal(7, "Alpaca (Spotted)", 8),
    ],
  },
  {
    identifier: "douc_2",
    stars: 3,
    area: "MAIN_ZOO",
    name: "2. Douc",
    requirements: [
      animal(10, "Lion Tamarin (Golden-Headed)", 0),
      animal(10, "Proboscis Monkey", 1),
      animal(10, "Mountain Gorilla (White)", 2),
      animal(10, "De Brazza's Monkey", 3),
      animal(10, "Japanese Macaque", 4),
      animal(10, "Golden Snub-Nosed Monkey", 5),
      animal(10, "Emperor Tamarin", 6),
      animal(10, "Silvery Greater Galago", 7),
      animal(10, "Howler Monkey", 8),
    ],
  },
  {
    identifier: "amazonian_manatee",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Amazonian Manatee",
    requirements: [
      animal(5, "Manatee", 0),
      animal(5, "Elephant Seal", 1),
      animal(5, "Ribbon Seal", 2),
      animal(5, "Hooded Seal", 3),
      animal(5, "Southern Sea Lion", 4),
      animal(5, "Walrus", 5),
      animal(5, "Giant Oceanic Manta Ray", 6),
      animal(5, "Hawksbill Sea Turtle", 7),
      animal(5, "Orca", 8),
    ],
  },
  {
    identifier: "nilgai",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Nilgai",
    requirements: [
      animal(5, "Black Wildebeest", 0),
      animal(5, "Himalayan Tahr", 1),
      animal(5, "African Buffalo", 2),
      animal(5, "Pronghorn", 3),
      animal(5, "Dikdik", 4),
      animal(5, "Golden Takin", 5),
      animal(5, "Sheep", 6),
      animal(5, "Oryx", 7),
      animal(5, "Yak", 8),
    ],
  },
  {
    identifier: "bearded_vulture_red",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Bearded Vulture (Red)",
    requirements: [
      animal(8, "Bearded Vulture", 0),
      animal(8, "Secretarybird", 1),
      animal(8, "White-Headed Vulture", 2),
      animal(8, "Harpy Eagle", 3),
      animal(8, "Andean Condor", 4),
      animal(8, "Eastern Grass Owl", 5),
      animal(8, "Spot-Bellied Eagle-Owl", 6),
      animal(8, "White-Faced Owl", 7),
      animal(8, "Snowy Owl", 8),
    ],
  },
  {
    identifier: "white_crested_porcupine",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Crested Porcupine",
    requirements: [
      animal(5, "Crested Porcupine", 0),
      animal(5, "Canadian Porcupine", 1),
      animal(5, "Mexican Tree Porcupine", 2),
      animal(5, "Long-Eared Hedgehog", 3),
      animal(5, "Short-Beaked Echidna", 4),
    ],
  },
  {
    identifier: "nilgai_2",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Nilgai 2",
    requirements: [
      animal(5, "Alpine Ibex", 0),
      animal(5, "American Bison", 1),
      animal(5, "Bongo Antelope", 2),
      animal(5, "Domestic Goat", 3),
      animal(5, "Domestic Goat White", 4),
      animal(5, "Rocky Mountain Goat", 5),
      animal(5, "Musk Ox", 6),
      animal(5, "Banteng", 7),
      animal(5, "Impala", 8),
    ],
  },
  {
    identifier: "white_wild_boar",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Wild Boar",
    requirements: [
      decoration("Giant Tortoise Statue", 0),
      decoration("Kodiak Bear Statue", 1),
      decoration("Moose Statue", 2),
      decoration("Red Kangaroo Statue", 3),
      decoration("Red Fox Statue", 4),
      decoration("Bald Eagle Statue", 5),
      decoration("Koala Statue", 6),
      decoration("Plains Zebra Statue", 7),
      decoration("Wild Boar Statue", 8),
    ],
  },
  {
    identifier: "white_flamingo",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Flamingo",
    requirements: [
      decoration("Domestic Pig Statue", 0),
      decoration("Chimpanzee Statue", 1),
      decoration("Lion Statue", 2),
      decoration("Common Ostrich Statue", 3),
      decoration("Scarlet Macaw Statue", 4),
      decoration("Red Panda Statue", 5),
      decoration("Reticulated Giraffe Statue", 6),
      decoration("White Rhinoceros Statue", 7),
      decoration("Flamingo Statue", 8),
    ],
  },
  {
    identifier: "white_mandrill",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Mandrill",
    requirements: [
      decoration("Moon Bear Statue", 0),
      decoration("Komodo Dragon Statue", 1),
      decoration("Aardvark Statue", 2),
      decoration("Polar Bear Statue", 3),
      decoration("Tapir Statue", 4),
      decoration("Hippopotamus Statue", 5),
      decoration("Ocelot Statue", 6),
      decoration("Emperor Penguin Statue", 7),
      decoration("Mandrill Statue", 8),
    ],
  },
  {
    identifier: "amazon_river_dolphin_1",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Amazon River Dolphin I",
    requirements: [
      animal(5, "American Badger", 0),
      animal(5, "Rabbit (Harlequin)", 1),
      animal(5, "Reindeer (White)", 2),
      animal(5, "Stoat (Ermine)", 3),
      animal(5, "Kiwi (Spotted)", 4),
      animal(5, "Douc", 5),
      animal(5, "Bearded Vulture (Red)", 6),
      animal(5, "Brushtail Possum (Brown)", 7),
    ],
  },
  {
    identifier: "amazon_river_dolphin_2",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Amazon River Dolphin II",
    requirements: [
      animal(5, "Ferret Badger (Brown)", 0),
      animal(5, "Savannah Monitor (Light)", 1),
      animal(5, "Mandrill (White)", 2),
      animal(5, "Flamingo (White)", 3),
      animal(5, "Wild Boar (White)", 4),
      animal(5, "Manatee (Amazonian)", 5),
      animal(5, "Axolotl (White)", 6),
      animal(5, "Nilgai", 7),
      animal(5, "Crested Porcupine (White)", 8),
    ],
  },
  {
    identifier: "leucistic_elephant",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Leucistic Elephant",
    requirements: [
      decoration("Okapi Statue", 0),
      decoration("Panther Statue", 1),
      decoration("Green Anaconda Statue", 2),
      decoration("African Elephant Statue", 3),
      decoration("Nile Crocodile Statue", 4),
      decoration("Snow Hare Statue", 5),
      decoration("Western Crowned Pigeon Statue", 6),
    ],
  },
  {
    identifier: "leucistic_peafowl",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Leucistic Peafowl",
    requirements: [
      decoration("Peafowl Statue", 0),
      decoration("Lynx Statue", 1),
      decoration("Armadillo Statue", 2),
      decoration("Wolf Statue", 3),
      decoration("Alpaca Statue", 4),
      decoration("Baboon Statue", 5),
      decoration("American Bison Statue", 6),
    ],
  },
  {
    identifier: "albino_humpback_whale",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Albino Humpback Whale",
    requirements: [
      animal(10, "Rabbit (Spotted)", 0),
      animal(10, "Red Kangaroo (White)", 1),
      animal(10, "Flamingo (Black)", 2),
      animal(10, "Reticulated Giraffe (Black)", 3),
      animal(10, "Toco Toucan (White)", 4),
      animal(10, "Goodfellow Tree Kangaroo (Lumholtz)", 5),
      animal(10, "Oryx (Arabian)", 6),
      animal(10, "Musk Deer (Gold)", 7),
      animal(10, "Jaguarundi (Red)", 8),
    ],
  },
  {
    identifier: "gray_arctic_wolf",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Gray Arctic Wolf",
    requirements: [
      decoration("Secretarybird Statue", 0),
      decoration("European Badger Statue", 1),
      decoration("African Wild Ass Statue", 2),
      decoration("Toucan Statue", 3),
      decoration("Arctic Fox Statue", 4),
      decoration("Arctic Wolf Statue", 5),
    ],
  },
  {
    identifier: "giant_freshwater_stingray",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Giant Freshwater Stingray",
    requirements: [
      animal(10, "Amazon River Dolphin", 0),
      animal(10, "Dugong", 1),
      animal(10, "Oarfish", 2),
      animal(10, "Argali", 3),
      animal(10, "Lesser Flamingo", 4),
      animal(10, "Giant Rabbit", 5),
      animal(10, "Straw-Necked Ibis", 6),
      animal(10, "Mountain Nyala", 7),
      animal(10, "Blue-Eyed Black Lemur", 8),
    ],
  },
  {
    identifier: "giant_freshwater_stingray_2",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Giant Freshwater Stingray 2",
    requirements: [
      animal(10, "Amazon River Dolphin", 0),
      animal(10, "Common Genet (Brown)", 1),
      animal(10, "Indian Star Tortoise (Green)", 2),
      animal(10, "Sable (Red)", 3),
      animal(10, "Red Ruffed Lemur (Black-and-White)", 4),
      animal(10, "Lady Amherst's Pheasant", 5),
      animal(10, "Western Lowland Gorilla", 6),
      animal(10, "Sumatran Rhinoceros", 7),
      animal(10, "Angora Rabbit", 8),
    ],
  },
  {
    identifier: "ornate_wobbegong",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Ornate Wobbegong",
    requirements: [
      animal(10, "Tiger Shark", 0),
      animal(10, "Great White Shark", 1),
      animal(10, "Giant Oceanic Manta Ray", 2),
      animal(10, "Sawfish", 3),
      animal(10, "Bottle Nosed Dolphin", 4),
      animal(10, "Beluga Whale", 5),
      animal(10, "Orca", 6),
      animal(10, "Narwhal", 7),
      animal(10, "Commerson's Dolphin", 8),
    ],
  },
  {
    identifier: "ornate_wobbegong_2",
    stars: 3,
    area: "MAIN_ZOO",
    name: "Ornate Wobbegong 2",
    requirements: [
      animal(10, "Hammerhead Shark", 0),
      animal(10, "Reef Manta Ray", 1),
      animal(10, "Occellate River Stingray", 2),
      animal(10, "Humpback Whale", 3),
      animal(10, "Irrawaddy Dolphin", 4),
      animal(10, "Vaquita", 5),
      animal(10, "Ganges River Dolphin", 6),
      animal(10, "Leopard Seal", 7),
      animal(10, "Saimaa Ringed Seal", 8),
    ],
  },
  {
    identifier: "african_wolf_1",
    stars: 3,
    area: "MAIN_ZOO",
    name: "African Wolf 1",
    requirements: [
      animal(10, "Wolf", 0),
      animal(10, "Maned Wolf", 1),
      animal(10, "Cape Fox", 2),
      animal(10, "Culpeo", 3),
      animal(10, "Ethiopian Wolf", 4),
      animal(10, "Spectacled Bear", 5),
      animal(10, "Bush Dog", 6),
      animal(10, "Bat-eared Fox", 7),
      animal(10, "Perentie", 8),
    ],
  },
  {
    identifier: "african_wolf_2",
    stars: 3,
    area: "MAIN_ZOO",
    name: "African Wolf 2",
    requirements: [
      animal(10, "Tundra Wolf", 0),
      animal(10, "Arctic Wolf", 1),
      animal(10, "Dingo", 2),
      animal(10, "Short-Eared Zorro", 3),
      animal(10, "Black-Backed Jackal", 4),
      animal(10, "Dhole", 5),
      animal(10, "Sumatran Rhinoceros", 6),
      animal(10, "Grévy's Zebra", 7),
      animal(10, "African Wild Dog", 8),
    ],
  },
  {
    identifier: "white_reticulated_giraffe",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Reticulated Giraffe",
    requirements: [
      animal(10, "Reticulated Giraffe", 0),
      animal(10, "Masai Giraffe", 1),
      animal(10, "Red Fox (Leucistic)", 2),
      animal(10, "Lynx (Light)", 3),
      animal(10, "Snow Sheep (White)", 4),
      animal(10, "Cougar (White)", 5),
      animal(10, "Emu (Leucistic)", 6),
      animal(10, "Alpaca (White)", 7),
      animal(10, "African Elephant (Leucistic)", 8),
    ],
  },
  {
    identifier: "white_sumatran_tiger",
    stars: 3,
    area: "MAIN_ZOO",
    name: "White Sumatran Tiger",
    requirements: [
      decoration("Northern Pudu Statue", 0),
      decoration("Beaver Statue", 1),
      decoration("Snowy Owl Statue", 2),
      decoration("Mandarin Duck Statue", 3),
      decoration("Lion Statue", 4),
      decoration("Lynx Statue", 5),
      decoration("Ocelot Statue", 6),
      decoration("Emperor Penguin Statue", 7),
      decoration("Panther Statue", 8),
    ],
  },

  // ===== TERRARIUM - 2 star =====
  {
    identifier: "light_savannah_monitor",
    stars: 2,
    area: "TERRARIUM",
    name: "Light Savannah Monitor",
    requirements: [
      animal(3, "Savannah Monitor", 0),
      animal(3, "Long-Eared Hedgehog", 1),
      animal(3, "Numbat", 2),
      animal(3, "Horned Lizard", 3),
      animal(3, "Armadillo Girdled Lizard", 4),
      animal(3, "Asian Garden Dormouse", 5),
    ],
  },

  // ===== TERRARIUM - 3 star =====
  {
    identifier: "brown_ferret_badger",
    stars: 3,
    area: "TERRARIUM",
    name: "Brown Ferret Badger",
    requirements: [
      animal(7, "Ferret Badger", 0),
      animal(7, "Hazel Dormouse", 1),
      animal(7, "Eastern Chipmunk", 2),
      animal(7, "Maned Rat", 3),
      animal(7, "Least Weasel", 4),
      animal(7, "Red-Eyed Tree Frog", 5),
      animal(7, "Murine Mouse Opossum", 6),
      animal(7, "Madagascar Day Gecko", 7),
      animal(7, "Green-and-Black Poison Dart Frog", 8),
    ],
  },
  {
    identifier: "brown_pacman_frog",
    stars: 3,
    area: "TERRARIUM",
    name: "Brown Pacman Frog",
    requirements: [
      animal(10, "Pacman Frog", 0),
      animal(10, "Ili Pika", 1),
      animal(10, "Lowland Streaked Tenrec", 2),
      animal(10, "Silky Anteater", 3),
      animal(10, "Fire Salamander", 4),
      animal(10, "Emperor Scorpion", 5),
      animal(10, "Pink-Winged Stick Insect", 6),
      animal(10, "Yellow-Throated Marten", 7),
      animal(10, "Variegated Squirrel", 8),
    ],
  },

  // ===== AQUARIUM - 1 star =====
  {
    identifier: "discus_fish_light_blue",
    stars: 1,
    area: "AQUARIUM",
    name: "Discus Fish (Light-Blue)",
    requirements: [
      animal(2, "Discus", 0),
      animal(2, "Discus (Striped)", 1),
      animal(2, "Goldfish", 2),
      animal(2, "Goldfish (White)", 3),
      animal(2, "Red-Bellied Piranha", 4),
      animal(2, "Red-Bellied Piranha (Orange-Blue)", 5),
      animal(2, "Siamese Fighting Fish", 6),
      animal(2, "Siamese Fighting Fish (Halfmoon Butterfly)", 7),
    ],
  },

  // ===== AQUARIUM - 2 star =====
  {
    identifier: "axolotl_yellow",
    stars: 2,
    area: "AQUARIUM",
    name: "Axolotl (Yellow)",
    requirements: [
      animal(2, "Axolotl", 0),
      animal(2, "Discus (Light-Blue)", 1),
      animal(2, "Peacock Eel", 2),
      animal(2, "Compass Jellyfish (Spotted)", 3),
      animal(2, "Clownfish (Black)", 4),
      animal(2, "Dumbo Octopus (Red-and-White)", 5),
      animal(2, "Vampire Squid", 6),
      animal(2, "Yellow Boxfish", 7),
    ],
  },

  // ===== AQUARIUM - 3 star =====
  {
    identifier: "axolotl_white",
    stars: 3,
    area: "AQUARIUM",
    name: "Axolotl (White)",
    requirements: [
      animal(2, "Discus", 0),
      animal(2, "Goldfish", 1),
      animal(2, "Compass Jellyfish", 2),
      animal(2, "Clownfish", 3),
      animal(2, "Royal Blue Tang", 4),
      animal(2, "Mandarinfish", 5),
      animal(2, "Axolotl", 6),
    ],
  },
  {
    identifier: "leafy_seadragon_burgundy",
    stars: 3,
    area: "AQUARIUM",
    name: "Leafy Seadragon (Burgundy)",
    requirements: [
      animal(3, "Leafy Seadragon", 0),
      animal(3, "Short-Snouted Seahorse", 1),
      animal(3, "Compass Jellyfish", 2),
      animal(3, "Masked Puffer", 3),
      animal(3, "Luna Lionfish", 4),
      animal(3, "Mimic Octopus", 5),
      animal(3, "Striated Frogfish", 6),
      animal(3, "Mandarinfish (Light Blue)", 7),
      animal(3, "Mandarinfish (Brown)", 8),
    ],
  },

  // ===== NOCTARIUM - 3 star =====
  {
    identifier: "common_vampire_bat_beige",
    stars: 3,
    area: "NOCTARIUM",
    name: "Common Vampire Bat (Beige)",
    requirements: [
      animal(5, "Common Vampire Bat", 0),
      animal(5, "Slow Loris", 1),
      animal(5, "Springhare", 2),
      animal(5, "Tawny Frogmouth", 3),
      animal(5, "Southern Three-Banded Armadillo", 4),
      animal(5, "Lesser Hedgehog Tenrec", 5),
      animal(5, "Dwarf Hamster", 6),
      animal(5, "Pearl-Spotted Owlet", 7),
      animal(5, "Quoll", 8),
    ],
  },

  // ===== AVIARY - 3 star =====
  {
    identifier: "kingfisher_turquoise",
    stars: 3,
    area: "AVIARY",
    name: "Kingfisher (Turquoise)",
    requirements: [
      animal(5, "Kingfisher", 0),
      animal(5, "Amethyst Starling", 1),
      animal(5, "Eurasian Hoopoe", 2),
      animal(5, "Eurasian Golden Oriole", 3),
      animal(5, "Red Cardinal", 4),
      animal(5, "Resplendent Quetzal", 5),
      animal(5, "Shima Enaga", 6),
    ],
  },
];

async function main() {
  console.log("Seeding collections...");

  for (const col of collections) {
    const created = await prisma.collection.upsert({
      where: { identifier: col.identifier },
      update: {},
      create: {
        identifier: col.identifier,
        stars: col.stars,
        area: col.area,
        texts: {
          create: [
            { languageCode: "de", name: col.name },
            { languageCode: "en", name: col.name },
            { languageCode: "da", name: col.name },
            { languageCode: "nl", name: col.name },
            { languageCode: "es", name: col.name },
            { languageCode: "fr", name: col.name },
          ],
        },
        requirements: {
          create: col.requirements.map((r) => ({
            type: r.type,
            requiredLevel: r.requiredLevel ?? null,
            itemName: r.itemName,
            sortOrder: r.sortOrder,
          })),
        },
      },
    });
    console.log(`  ✓ ${created.identifier}`);
  }

  console.log(`Done. Seeded ${collections.length} collections.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
